-- ============================================================
-- RetrouvIt — V1 : schéma de référence (baseline)
-- Généré depuis les entités JPA (hibernate.ddl-auto=update)
-- 27 tables. Compatible PostgreSQL 16.
-- ============================================================
--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_alerts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_alerts (
    id bigint NOT NULL,
    acknowledged boolean NOT NULL,
    acknowledged_at timestamp(6) without time zone,
    category character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    current_value bigint NOT NULL,
    level character varying(255) NOT NULL,
    message text NOT NULL,
    threshold_value bigint NOT NULL,
    title character varying(255) NOT NULL,
    CONSTRAINT admin_alerts_level_check CHECK (((level)::text = ANY ((ARRAY['INFO'::character varying, 'WARNING'::character varying, 'CRITICAL'::character varying])::text[])))
);


--
-- Name: admin_alerts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin_alerts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_alerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alert_thresholds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alert_thresholds (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255),
    enabled boolean NOT NULL,
    level character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    value bigint NOT NULL,
    CONSTRAINT alert_thresholds_level_check CHECK (((level)::text = ANY ((ARRAY['INFO'::character varying, 'WARNING'::character varying, 'CRITICAL'::character varying])::text[])))
);


--
-- Name: alert_thresholds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.alert_thresholds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alert_thresholds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    enabled boolean NOT NULL,
    icon character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    sort_order integer NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: certification_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.certification_requests (
    id bigint NOT NULL,
    active_status boolean NOT NULL,
    admin_notes text,
    created_at timestamp(6) without time zone,
    document_type character varying(255) NOT NULL,
    document_url character varying(255) NOT NULL,
    rejection_reason text,
    return_count_at_submission integer NOT NULL,
    reviewed_at timestamp(6) without time zone,
    reviewed_by bigint,
    selfie_url character varying(255),
    status character varying(255) NOT NULL,
    trust_score_at_submission integer NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    CONSTRAINT certification_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying, 'SUSPENDED'::character varying])::text[])))
);


--
-- Name: certification_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.certification_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.certification_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cities (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    enabled boolean NOT NULL,
    name character varying(255) NOT NULL,
    region character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: cities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conversations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversations (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    last_message character varying(255),
    last_message_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    unread_count integer NOT NULL,
    updated_at timestamp(6) without time zone,
    created_by_id bigint,
    user1_id bigint NOT NULL,
    user2_id bigint NOT NULL,
    CONSTRAINT conversations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACTIVE'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: conversations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.conversations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: escrows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.escrows (
    id bigint NOT NULL,
    amount bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    deadline date NOT NULL,
    location character varying(255),
    progress integer NOT NULL,
    reference character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    buyer_id bigint NOT NULL,
    found_object_id bigint,
    lost_object_id bigint,
    seller_id bigint NOT NULL,
    CONSTRAINT escrows_status_check CHECK (((status)::text = ANY ((ARRAY['AWAITING_RETURN'::character varying, 'LOCKED'::character varying, 'RETURN_CONFIRMED'::character varying, 'RELEASE_PENDING'::character varying, 'RELEASED'::character varying, 'COMPLETED'::character varying, 'REFUNDED'::character varying, 'DISPUTED'::character varying])::text[])))
);


--
-- Name: escrows_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.escrows ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.escrows_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: found_objects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.found_objects (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    date_found date NOT NULL,
    description text NOT NULL,
    image character varying(255),
    images character varying(255),
    location character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    views integer NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT found_objects_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'MATCHED'::character varying, 'FOUND'::character varying, 'RESOLVED'::character varying, 'RETURNED'::character varying, 'EXPIRED'::character varying])::text[])))
);


--
-- Name: found_objects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.found_objects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.found_objects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lost_objects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lost_objects (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    date_lost date NOT NULL,
    description text NOT NULL,
    image character varying(255),
    images character varying(255),
    location character varying(255) NOT NULL,
    reward bigint,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    views integer NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT lost_objects_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'MATCHED'::character varying, 'FOUND'::character varying, 'RESOLVED'::character varying, 'RETURNED'::character varying, 'EXPIRED'::character varying])::text[])))
);


--
-- Name: lost_objects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lost_objects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lost_objects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.matches (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    match_score integer NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    found_object_id bigint NOT NULL,
    lost_object_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT matches_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'REJECTED'::character varying, 'COMPLETED'::character varying])::text[])))
);


--
-- Name: matches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.matches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meetings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meetings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    latitude double precision,
    location character varying(500) NOT NULL,
    longitude double precision,
    meeting_date_time timestamp(6) without time zone NOT NULL,
    notes text,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    proposed_by_id bigint NOT NULL,
    return_request_id bigint NOT NULL,
    CONSTRAINT meetings_status_check CHECK (((status)::text = ANY ((ARRAY['PROPOSED'::character varying, 'ACCEPTED'::character varying, 'MODIFIED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying])::text[])))
);


--
-- Name: meetings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.meetings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meetings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    audio_url character varying(255),
    content text,
    created_at timestamp(6) without time zone,
    deleted boolean NOT NULL,
    image_url character varying(255),
    read boolean NOT NULL,
    conversation_id bigint NOT NULL,
    reply_to_id bigint,
    sender_id bigint NOT NULL
);


--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: negotiation_offers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.negotiation_offers (
    id bigint NOT NULL,
    amount bigint NOT NULL,
    created_at timestamp(6) without time zone,
    message text,
    status character varying(255) NOT NULL,
    offered_by_id bigint NOT NULL,
    parent_offer_id bigint,
    return_request_id bigint NOT NULL,
    CONSTRAINT negotiation_offers_status_check CHECK (((status)::text = ANY ((ARRAY['PROPOSED'::character varying, 'COUNTERED'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: negotiation_offers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.negotiation_offers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.negotiation_offers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    conversation_id bigint,
    created_at timestamp(6) without time zone,
    created_by_user_id bigint,
    description text NOT NULL,
    read boolean NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['MATCH'::character varying, 'MESSAGE'::character varying, 'CLAIM'::character varying, 'SYSTEM'::character varying, 'PAYMENT'::character varying, 'CONVERSATION_REQUEST'::character varying])::text[])))
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: object_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.object_comments (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    deleted boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    found_object_id bigint,
    lost_object_id bigint,
    parent_id bigint,
    user_id bigint NOT NULL
);


--
-- Name: object_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.object_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.object_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: object_likes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.object_likes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    found_object_id bigint,
    lost_object_id bigint,
    user_id bigint NOT NULL
);


--
-- Name: object_likes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.object_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.object_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    used boolean NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    currency character varying(255) NOT NULL,
    external_reference character varying(255),
    failure_reason character varying(255),
    method character varying(255) NOT NULL,
    phone_number character varying(255),
    provider character varying(255) NOT NULL,
    reference character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    CONSTRAINT payments_method_check CHECK (((method)::text = ANY ((ARRAY['MOBILE_MONEY'::character varying, 'CARD'::character varying, 'WALLET'::character varying])::text[]))),
    CONSTRAINT payments_provider_check CHECK (((provider)::text = ANY ((ARRAY['MTN_MOMO'::character varying, 'ORANGE_MONEY'::character varying, 'WAVE'::character varying])::text[]))),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying])::text[])))
);


--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: platform_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.platform_settings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255) NOT NULL,
    setting_key character varying(255) NOT NULL,
    setting_type character varying(255) NOT NULL,
    setting_value text NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: platform_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.platform_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.platform_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proofs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proofs (
    id bigint NOT NULL,
    additional_info_requests integer NOT NULL,
    characteristics text,
    condition character varying(100),
    created_at timestamp(6) without time zone,
    description text,
    discovery_date_time timestamp(6) without time zone,
    discovery_location character varying(255),
    photos text,
    review_note text,
    serial_number character varying(255),
    status character varying(255) NOT NULL,
    technical_info text,
    updated_at timestamp(6) without time zone,
    return_request_id bigint NOT NULL,
    submitted_by_id bigint NOT NULL,
    CONSTRAINT proofs_status_check CHECK (((status)::text = ANY ((ARRAY['SUBMITTED'::character varying, 'NEED_MORE_INFO'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: proofs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.proofs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proofs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ratings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ratings (
    id bigint NOT NULL,
    comment text,
    created_at timestamp(6) without time zone,
    stars integer NOT NULL,
    updated_at timestamp(6) without time zone,
    rated_id bigint NOT NULL,
    rater_id bigint NOT NULL,
    return_request_id bigint NOT NULL
);


--
-- Name: ratings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ratings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ratings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone NOT NULL,
    revoked boolean NOT NULL,
    token text NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reports (
    id bigint NOT NULL,
    amount bigint,
    created_at timestamp(6) without time zone,
    description text NOT NULL,
    priority character varying(255) NOT NULL,
    related_transaction bigint,
    resolution text,
    resolved_by bigint,
    status character varying(255) NOT NULL,
    subject character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    found_object_id bigint,
    lost_object_id bigint,
    reported_id bigint,
    reporter_id bigint NOT NULL,
    CONSTRAINT reports_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_REVIEW'::character varying, 'RESOLVED'::character varying, 'DISMISSED'::character varying, 'ESCALATED'::character varying])::text[]))),
    CONSTRAINT reports_type_check CHECK (((type)::text = ANY ((ARRAY['FRAUD'::character varying, 'SCAM'::character varying, 'FAKE_LISTING'::character varying, 'HARASSMENT'::character varying, 'PAYMENT_DISPUTE'::character varying, 'IDENTITY'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: return_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.return_requests (
    id bigint NOT NULL,
    accepted_amount bigint,
    collaboration_started_at timestamp(6) without time zone,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    dispute_reason text,
    dispute_resolution text,
    dispute_resolved boolean,
    disputed_by bigint,
    finder_return_confirmed boolean,
    finder_validated boolean,
    loser_return_confirmed boolean,
    loser_validated boolean,
    meeting_date timestamp(6) without time zone,
    meeting_lat double precision,
    meeting_lng double precision,
    meeting_location character varying(255),
    payment_amount bigint,
    platform_fee bigint,
    platform_fee_pct integer NOT NULL,
    proof_status character varying(255),
    proposed_amount bigint,
    reference character varying(255) NOT NULL,
    released_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    escrow_id bigint,
    finder_id bigint NOT NULL,
    found_object_id bigint,
    loser_id bigint NOT NULL,
    lost_object_id bigint,
    CONSTRAINT return_requests_proof_status_check CHECK (((proof_status)::text = ANY ((ARRAY['SUBMITTED'::character varying, 'NEED_MORE_INFO'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[]))),
    CONSTRAINT return_requests_status_check CHECK (((status)::text = ANY ((ARRAY['MATCH_FOUND'::character varying, 'PROOF_SUBMITTED'::character varying, 'NEED_MORE_INFO'::character varying, 'OWNER_CONFIRMED'::character varying, 'REJECTED'::character varying, 'NEGOTIATING'::character varying, 'REWARD_ACCEPTED'::character varying, 'PAYMENT_PENDING'::character varying, 'PAYMENT_FAILED'::character varying, 'PAYMENT_LOCKED'::character varying, 'COLLABORATION_ACTIVE'::character varying, 'RETURN_IN_PROGRESS'::character varying, 'RETURN_CONFIRMED'::character varying, 'RELEASE_PENDING'::character varying, 'RELEASED'::character varying, 'COMPLETED'::character varying, 'DISPUTED'::character varying, 'DISPUTE_RESOLVED'::character varying, 'SUPPORT_REVIEW'::character varying, 'REFUNDED'::character varying, 'CANCELLED'::character varying, 'CHAT_INITIATED'::character varying, 'PAYMENT_COMPLETED'::character varying])::text[])))
);


--
-- Name: return_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.return_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.return_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: saved_objects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.saved_objects (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    found_object_id bigint,
    lost_object_id bigint,
    user_id bigint NOT NULL
);


--
-- Name: saved_objects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.saved_objects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saved_objects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    amount bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description text NOT NULL,
    status character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT transactions_type_check CHECK (((type)::text = ANY ((ARRAY['REWARD'::character varying, 'ESCROW'::character varying, 'WITHDRAWAL'::character varying, 'REFUND'::character varying, 'DEPOSIT'::character varying])::text[])))
);


--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    avatar character varying(255),
    ban_reason character varying(255),
    banned boolean NOT NULL,
    banned_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    location character varying(255),
    matches integer NOT NULL,
    name character varying(255) NOT NULL,
    objects_found integer NOT NULL,
    objects_lost integer NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(255),
    role character varying(255) NOT NULL,
    trust_score integer NOT NULL,
    updated_at timestamp(6) without time zone,
    verified boolean NOT NULL,
    wallet_balance bigint NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_alerts admin_alerts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_alerts
    ADD CONSTRAINT admin_alerts_pkey PRIMARY KEY (id);


--
-- Name: alert_thresholds alert_thresholds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_thresholds
    ADD CONSTRAINT alert_thresholds_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: certification_requests certification_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certification_requests
    ADD CONSTRAINT certification_requests_pkey PRIMARY KEY (id);


--
-- Name: cities cities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);


--
-- Name: conversations conversations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_pkey PRIMARY KEY (id);


--
-- Name: escrows escrows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escrows
    ADD CONSTRAINT escrows_pkey PRIMARY KEY (id);


--
-- Name: found_objects found_objects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.found_objects
    ADD CONSTRAINT found_objects_pkey PRIMARY KEY (id);


--
-- Name: lost_objects lost_objects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lost_objects
    ADD CONSTRAINT lost_objects_pkey PRIMARY KEY (id);


--
-- Name: matches matches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_pkey PRIMARY KEY (id);


--
-- Name: meetings meetings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT meetings_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: negotiation_offers negotiation_offers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.negotiation_offers
    ADD CONSTRAINT negotiation_offers_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: object_comments object_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.object_comments
    ADD CONSTRAINT object_comments_pkey PRIMARY KEY (id);


--
-- Name: object_likes object_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.object_likes
    ADD CONSTRAINT object_likes_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: platform_settings platform_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platform_settings
    ADD CONSTRAINT platform_settings_pkey PRIMARY KEY (id);


--
-- Name: proofs proofs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proofs
    ADD CONSTRAINT proofs_pkey PRIMARY KEY (id);


--
-- Name: ratings ratings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ratings
    ADD CONSTRAINT ratings_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: reports reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_pkey PRIMARY KEY (id);


--
-- Name: return_requests return_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT return_requests_pkey PRIMARY KEY (id);


--
-- Name: saved_objects saved_objects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_objects
    ADD CONSTRAINT saved_objects_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: ratings uk45wn7g88naeydvye6vqqnewek; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ratings
    ADD CONSTRAINT uk45wn7g88naeydvye6vqqnewek UNIQUE (return_request_id, rater_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: password_reset_tokens uk71lqwbwtklmljk3qlsugr1mig; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);


--
-- Name: object_likes uk7i1d8b5q2b4adfb3g3pujyrd0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.object_likes
    ADD CONSTRAINT uk7i1d8b5q2b4adfb3g3pujyrd0 UNIQUE (user_id, lost_object_id);


--
-- Name: saved_objects uka6q6nldpagqg1u7wrx2a42thy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_objects
    ADD CONSTRAINT uka6q6nldpagqg1u7wrx2a42thy UNIQUE (user_id, found_object_id);


--
-- Name: platform_settings ukayks1ajfa52rvppxmhanlyvht; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platform_settings
    ADD CONSTRAINT ukayks1ajfa52rvppxmhanlyvht UNIQUE (setting_key);


--
-- Name: saved_objects ukfa11gvkx2ss4l0hwseua3q2fc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_objects
    ADD CONSTRAINT ukfa11gvkx2ss4l0hwseua3q2fc UNIQUE (user_id, lost_object_id);


--
-- Name: object_likes ukh6e7keyjtvsjq5cmm148ucbdt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.object_likes
    ADD CONSTRAINT ukh6e7keyjtvsjq5cmm148ucbdt UNIQUE (user_id, found_object_id);


--
-- Name: alert_thresholds ukk5o82xswvwiewr2pibknjh6d8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_thresholds
    ADD CONSTRAINT ukk5o82xswvwiewr2pibknjh6d8 UNIQUE (category, level);


--
-- Name: cities ukl61tawv0e2a93es77jkyvi7qa; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT ukl61tawv0e2a93es77jkyvi7qa UNIQUE (name);


--
-- Name: categories ukt8o6pivur7nn124jehx7cygw5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);


--
-- Name: payments ukxqxnoljqu6mkrkwwcnfisx38; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT ukxqxnoljqu6mkrkwwcnfisx38 UNIQUE (reference);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: negotiation_offers fk139lc31hww6dvxo3a8hgfdmlp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.negotiation_offers
    ADD CONSTRAINT fk139lc31hww6dvxo3a8hgfdmlp FOREIGN KEY (return_request_id) REFERENCES public.return_requests(id);


--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: object_likes fk2db9t813f7eyy8lemhpuk8nk4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.object_likes
    ADD CONSTRAINT fk2db9t813f7eyy8lemhpuk8nk4 FOREIGN KEY (lost_object_id) REFERENCES public.lost_objects(id);


--
-- Name: escrows fk2omjx50pfmkoreh60o5qin18x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escrows
    ADD CONSTRAINT fk2omjx50pfmkoreh60o5qin18x FOREIGN KEY (seller_id) REFERENCES public.users(id);


--
-- Name: escrows fk334gok5u8kob1ju85cxrtj2nf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escrows
    ADD CONSTRAINT fk334gok5u8kob1ju85cxrtj2nf FOREIGN KEY (buyer_id) REFERENCES public.users(id);


--
-- Name: messages fk4ui4nnwntodh6wjvck53dbk9m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk4ui4nnwntodh6wjvck53dbk9m FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- Name: saved_objects fk5tw9iupro6fsxiojs7l992x9t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_objects
    ADD CONSTRAINT fk5tw9iupro6fsxiojs7l992x9t FOREIGN KEY (found_object_id) REFERENCES public.found_objects(id);


--
-- Name: matches fk6ra1r2c5moy2buo5okukga74n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT fk6ra1r2c5moy2buo5okukga74n FOREIGN KEY (lost_object_id) REFERENCES public.lost_objects(id);


--
-- Name: ratings fk7onlds44wo2ch9el5bn5vwo1r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ratings
    ADD CONSTRAINT fk7onlds44wo2ch9el5bn5vwo1r FOREIGN KEY (return_request_id) REFERENCES public.return_requests(id);


--
-- Name: matches fk7onrut3d5ct8tx2ujho0g0nhq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT fk7onrut3d5ct8tx2ujho0g0nhq FOREIGN KEY (found_object_id) REFERENCES public.found_objects(id);


--
-- Name: reports fk7y22w95lj3mp6rs60nsteum0y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT fk7y22w95lj3mp6rs60nsteum0y FOREIGN KEY (found_object_id) REFERENCES public.found_objects(id);


--
-- Name: return_requests fk8f7b3a2k92o49x236btgplm9i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT fk8f7b3a2k92o49x236btgplm9i FOREIGN KEY (found_object_id) REFERENCES public.found_objects(id);


--
-- Name: conversations fk8wv0rmd8jb3cqcbyng15ubrmk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fk8wv0rmd8jb3cqcbyng15ubrmk FOREIGN KEY (user1_id) REFERENCES public.users(id);


--
-- Name: lost_objects fk9ldyinanlvpbeo0ojhkd9ppm0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lost_objects
    ADD CONSTRAINT fk9ldyinanlvpbeo0ojhkd9ppm0 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: object_likes fkac0ysflkjno9lyjxci2n6ikgp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.object_likes
    ADD CONSTRAINT fkac0ysflkjno9lyjxci2n6ikgp FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: ratings fkaltgx3c2jt7rui0lv8m660pr4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ratings
    ADD CONSTRAINT fkaltgx3c2jt7rui0lv8m660pr4 FOREIGN KEY (rated_id) REFERENCES public.users(id);


--
-- Name: meetings fkct1n242artle3517buu0vr8ib; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT fkct1n242artle3517buu0vr8ib FOREIGN KEY (return_request_id) REFERENCES public.return_requests(id);


--
-- Name: reports fkd3qiw2om5d2oh5xb7fbdcq225; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT fkd3qiw2om5d2oh5xb7fbdcq225 FOREIGN KEY (reporter_id) REFERENCES public.users(id);


--
-- Name: proofs fkd6cqc0jkqeqnpghhw44pve2dc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proofs
    ADD CONSTRAINT fkd6cqc0jkqeqnpghhw44pve2dc FOREIGN KEY (return_request_id) REFERENCES public.return_requests(id);


--
-- Name: object_comments fkdbiwlcmg4ot7piq31yc4hi39s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.object_comments
    ADD CONSTRAINT fkdbiwlcmg4ot7piq31yc4hi39s FOREIGN KEY (lost_object_id) REFERENCES public.lost_objects(id);


--
-- Name: conversations fke7w0k1xem21pp85wxh5moodnk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fke7w0k1xem21pp85wxh5moodnk FOREIGN KEY (user2_id) REFERENCES public.users(id);


--
-- Name: negotiation_offers fke85kwpoa0pibc7yajjgo7i1j9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.negotiation_offers
    ADD CONSTRAINT fke85kwpoa0pibc7yajjgo7i1j9 FOREIGN KEY (offered_by_id) REFERENCES public.users(id);


--
-- Name: return_requests fkepe16yaaum2dgulxpplxhhjp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT fkepe16yaaum2dgulxpplxhhjp FOREIGN KEY (loser_id) REFERENCES public.users(id);


--
-- Name: object_comments fkeqt816ah6srgjwqwjllx5pt51; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.object_comments
    ADD CONSTRAINT fkeqt816ah6srgjwqwjllx5pt51 FOREIGN KEY (found_object_id) REFERENCES public.found_objects(id);


--
-- Name: ratings fkfcvojhiy6y8q4eyh0oxvwth6n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ratings
    ADD CONSTRAINT fkfcvojhiy6y8q4eyh0oxvwth6n FOREIGN KEY (rater_id) REFERENCES public.users(id);


--
-- Name: messages fkg23x99if9xk265onv7btb0cg9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fkg23x99if9xk265onv7btb0cg9 FOREIGN KEY (reply_to_id) REFERENCES public.messages(id);


--
-- Name: proofs fkgo1h6f9vynxyvp4ldgg912xax; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proofs
    ADD CONSTRAINT fkgo1h6f9vynxyvp4ldgg912xax FOREIGN KEY (submitted_by_id) REFERENCES public.users(id);


--
-- Name: return_requests fkhfstpdx7gatwoeyk1lnj8qj6f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT fkhfstpdx7gatwoeyk1lnj8qj6f FOREIGN KEY (lost_object_id) REFERENCES public.lost_objects(id);


--
-- Name: object_comments fkigx6chd3v3khywxhoixd131se; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.object_comments
    ADD CONSTRAINT fkigx6chd3v3khywxhoixd131se FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: saved_objects fkikl08b5u3iccg106llq1an26b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_objects
    ADD CONSTRAINT fkikl08b5u3iccg106llq1an26b FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: negotiation_offers fkiuibv5sma5quqmtpj7sqexe4b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.negotiation_offers
    ADD CONSTRAINT fkiuibv5sma5quqmtpj7sqexe4b FOREIGN KEY (parent_offer_id) REFERENCES public.negotiation_offers(id);


--
-- Name: object_comments fkj4vxrdoucyl3hb0etbx8fyhs5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.object_comments
    ADD CONSTRAINT fkj4vxrdoucyl3hb0etbx8fyhs5 FOREIGN KEY (parent_id) REFERENCES public.object_comments(id);


--
-- Name: payments fkj94hgy9v5fw1munb90tar2eje; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkj94hgy9v5fw1munb90tar2eje FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: certification_requests fkjj6i4j16pn9s79an1isxlir4c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certification_requests
    ADD CONSTRAINT fkjj6i4j16pn9s79an1isxlir4c FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: matches fkjn5cea248gae6hjub299oyqlf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT fkjn5cea248gae6hjub299oyqlf FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: escrows fkk0k08m8nci3jwdlmj139gpa19; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escrows
    ADD CONSTRAINT fkk0k08m8nci3jwdlmj139gpa19 FOREIGN KEY (found_object_id) REFERENCES public.found_objects(id);


--
-- Name: password_reset_tokens fkk3ndxg5xp6v7wd4gjyusp15gq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: return_requests fkkcirx6sysdhhs3gwspfh6q4cc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT fkkcirx6sysdhhs3gwspfh6q4cc FOREIGN KEY (escrow_id) REFERENCES public.escrows(id);


--
-- Name: object_likes fkkp6usfrhieqi7qxjxd74we4tg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.object_likes
    ADD CONSTRAINT fkkp6usfrhieqi7qxjxd74we4tg FOREIGN KEY (found_object_id) REFERENCES public.found_objects(id);


--
-- Name: meetings fkmj47nu142pgympvg7lsmamrxp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT fkmj47nu142pgympvg7lsmamrxp FOREIGN KEY (proposed_by_id) REFERENCES public.users(id);


--
-- Name: found_objects fkmtw1jr6b7f9b5g7vwgckj8d4h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.found_objects
    ADD CONSTRAINT fkmtw1jr6b7f9b5g7vwgckj8d4h FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: reports fknvr3ioyjc7gaxq2dew3u61e7s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT fknvr3ioyjc7gaxq2dew3u61e7s FOREIGN KEY (lost_object_id) REFERENCES public.lost_objects(id);


--
-- Name: conversations fkq33k2jsvt4rvxsbfcqn5723x8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fkq33k2jsvt4rvxsbfcqn5723x8 FOREIGN KEY (created_by_id) REFERENCES public.users(id);


--
-- Name: transactions fkqwv7rmvc8va8rep7piikrojds; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkqwv7rmvc8va8rep7piikrojds FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: reports fks5hp3xww9pl0bwblxl3cfwue2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT fks5hp3xww9pl0bwblxl3cfwue2 FOREIGN KEY (reported_id) REFERENCES public.users(id);


--
-- Name: escrows fkt178vpjgcec0ysq1u87n2u0e6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escrows
    ADD CONSTRAINT fkt178vpjgcec0ysq1u87n2u0e6 FOREIGN KEY (lost_object_id) REFERENCES public.lost_objects(id);


--
-- Name: messages fkt492th6wsovh1nush5yl5jj8e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fkt492th6wsovh1nush5yl5jj8e FOREIGN KEY (conversation_id) REFERENCES public.conversations(id);


--
-- Name: return_requests fkt8mpc4jafeeeged0kf38n9c16; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT fkt8mpc4jafeeeged0kf38n9c16 FOREIGN KEY (finder_id) REFERENCES public.users(id);


--
-- Name: saved_objects fktn9iih9b5gb4amqtjx9i8oiwf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_objects
    ADD CONSTRAINT fktn9iih9b5gb4amqtjx9i8oiwf FOREIGN KEY (lost_object_id) REFERENCES public.lost_objects(id);


--
-- PostgreSQL database dump complete
--


