-- ============================================================
-- RetrouvIt — V3 : codes OTP pour l'authentification à deux
-- facteurs (2FA) par email — cahier des charges §5.1 / §6.1.
-- Stockage persistant (la stack n'inclut pas Redis) ; les règles
-- CDC sont respectées : code haché, expiration 5 min, usage
-- unique, 5 tentatives max, destination en clair pour l'envoi.
-- ============================================================

CREATE TABLE otp_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    code_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    consumed BOOLEAN NOT NULL DEFAULT FALSE,
    attempts INTEGER NOT NULL DEFAULT 0,
    purpose VARCHAR(32) NOT NULL DEFAULT 'LOGIN',
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_otp_purpose CHECK (purpose IN ('LOGIN', 'REGISTER', 'PASSWORD_RESET'))
);

CREATE INDEX idx_otp_email_active ON otp_codes (email, purpose, consumed);
