-- ============================================================
-- RetrouvIt — V6 : demandes de retrait vers Mobile Money
-- CDC §5.4 (POST /wallet/withdraw) et §8.2 (validation manuelle
-- finance au-delà d'un seuil anti-fraude paramétrable).
-- ============================================================

CREATE TABLE withdrawal_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    reference VARCHAR(255) NOT NULL UNIQUE,
    amount BIGINT NOT NULL,
    method VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    failure_reason VARCHAR(500),
    reviewed_by BIGINT,
    reviewed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_withdrawals_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT ck_withdrawals_status CHECK (status IN ('PENDING_REVIEW','PROCESSING','COMPLETED','FAILED','REJECTED'))
);

CREATE INDEX idx_withdrawals_user ON withdrawal_requests (user_id);
CREATE INDEX idx_withdrawals_status ON withdrawal_requests (status);
