-- ============================================================
-- RetrouvIt — V8 : flow de restitution conforme à la machine
-- d'états officielle (RetrouvIt-Flow-Restitution.md §25).
--
-- 1. return_requests.status : conversion des anciens statuts
--    vers la machine officielle, puis nouvelle contrainte CHECK.
-- 2. Question de vérification sur found_objects (§2 / CDC §4.2) :
--    la réponse n'est stockée QUE hachée (bcrypt), jamais en clair.
-- 3. return_requests.chercher_verification_failed : compteur
--    d'échecs de vérification (blocage après 5 essais).
-- ============================================================

-- ─── 1. Conversion des statuts ─────────────────────────────
-- Ancien → Nouveau (mapping sémantique) :
--   MATCH_FOUND            → MATCH_FOUND
--   PROOF_SUBMITTED        → VERIFICATION_PENDING (preuves = 1er mode de vérification)
--   NEED_MORE_INFO         → VERIFICATION_PENDING
--   OWNER_CONFIRMED        → VERIFIED
--   NEGOTIATING            → PROPOSAL_PENDING (proposition en discussion)
--   REWARD_ACCEPTED        → PAYMENT_PENDING
--   PAYMENT_PENDING        → PAYMENT_PENDING
--   PAYMENT_LOCKED         → ESCROW_FUNDED
--   COLLABORATION_ACTIVE   → CHAT_ACTIVE
--   RETURN_IN_PROGRESS     → MISSION_STARTED
--   RETURN_CONFIRMED       → HANDOVER_PENDING (release auto à venir)
--   RELEASE_PENDING        → HANDOVER_PENDING
--   RELEASED               → COMPLETED (fonds libérés = fin du flow)
--   PAYMENT_COMPLETED      → COMPLETED
--   DISPUTED               → DISPUTED
--   DISPUTE_RESOLVED       → RESOLVED
--   SUPPORT_REVIEW         → UNDER_REVIEW
--   REFUNDED               → REFUNDED
--   CANCELLED              → CANCELLED
--   CHAT_INITIATED         → CHAT_ACTIVE (compat ancien workflow)
--   REJECTED               → REJECTED
--   PAYMENT_FAILED         → PAYMENT_FAILED
--   COMPLETED              → COMPLETED (inchangé)

UPDATE return_requests SET status = CASE status
    WHEN 'PROOF_SUBMITTED'      THEN 'VERIFICATION_PENDING'
    WHEN 'NEED_MORE_INFO'       THEN 'VERIFICATION_PENDING'
    WHEN 'OWNER_CONFIRMED'      THEN 'VERIFIED'
    WHEN 'NEGOTIATING'          THEN 'PROPOSAL_PENDING'
    WHEN 'REWARD_ACCEPTED'      THEN 'PAYMENT_PENDING'
    WHEN 'PAYMENT_PENDING'      THEN 'PAYMENT_PENDING'
    WHEN 'PAYMENT_LOCKED'       THEN 'ESCROW_FUNDED'
    WHEN 'COLLABORATION_ACTIVE' THEN 'CHAT_ACTIVE'
    WHEN 'RETURN_IN_PROGRESS'   THEN 'MISSION_STARTED'
    WHEN 'RETURN_CONFIRMED'     THEN 'HANDOVER_PENDING'
    WHEN 'RELEASE_PENDING'      THEN 'HANDOVER_PENDING'
    WHEN 'RELEASED'             THEN 'COMPLETED'
    WHEN 'PAYMENT_COMPLETED'    THEN 'COMPLETED'
    WHEN 'DISPUTE_RESOLVED'     THEN 'RESOLVED'
    WHEN 'SUPPORT_REVIEW'       THEN 'UNDER_REVIEW'
    WHEN 'CHAT_INITIATED'       THEN 'CHAT_ACTIVE'
    ELSE status
END;

ALTER TABLE return_requests DROP CONSTRAINT IF EXISTS return_requests_status_check;

ALTER TABLE return_requests ADD CONSTRAINT return_requests_status_check
    CHECK (status IN (
        'MATCH_FOUND','VERIFICATION_PENDING','VERIFIED','CONNECTION_PENDING',
        'CHAT_ACTIVE','PROPOSAL_PENDING','PAYMENT_PENDING','ESCROW_FUNDED',
        'MISSION_READY','MISSION_STARTED','MEETING_IN_PROGRESS','HANDOVER_PENDING',
        'COMPLETED','REJECTED','PAYMENT_FAILED','DISPUTED','UNDER_REVIEW',
        'RESOLVED','REFUNDED','CANCELLED'
    ));

-- ─── 2. Question de vérification (found_objects) ───────────
ALTER TABLE found_objects ADD COLUMN verification_question VARCHAR(500);
ALTER TABLE found_objects ADD COLUMN verification_answer_hash VARCHAR(255);

-- ─── 3. Compteur d'échecs de vérification ──────────────────
ALTER TABLE return_requests ADD COLUMN verification_attempts INT NOT NULL DEFAULT 0;

-- ─── 4. Timeline d'audit de la collaboration (§24) ─────────
CREATE TABLE collaboration_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_request_id BIGINT NOT NULL,
    actor_id BIGINT,
    event_type VARCHAR(64) NOT NULL,
    description VARCHAR(500),
    metadata TEXT,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_collab_events_return FOREIGN KEY (return_request_id)
        REFERENCES return_requests(id) ON DELETE CASCADE
);

CREATE INDEX idx_collab_events_request ON collaboration_events (return_request_id, created_at);
