-- ============================================================
-- RetrouvIt — V9 : partage de position pendant la mission
-- (RetrouvIt-Flow-Restitution.md §13 / §20).
--
-- Principe de confidentialité :
--   Avant mission        → aucune position stockée/exposée
--   Mission démarrée     → positions temporairement disponibles
--   Restitution terminée → partage automatiquement désactivé (§20)
-- ============================================================

CREATE TABLE collaboration_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_request_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    accuracy_meters DOUBLE PRECISION,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_collab_loc_return FOREIGN KEY (return_request_id)
        REFERENCES return_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_collab_loc_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_collab_loc_user UNIQUE (return_request_id, user_id)
);

CREATE INDEX idx_collab_loc_request ON collaboration_locations (return_request_id);
